export const content = {
  ru: {
    title: "Павел Симонов · Разработчик",
    description:
      "Павел Симонов (Sipaha). Инструменты для разработчиков, открытые проекты и способы поддержать мою работу.",
    skip: "К содержимому",
    projectsNav: "Проекты",
    supportNav: "Поддержать",
    about: "О моей работе",
    aboutText:
      "Работаю над настольными приложениями и инструментами для разработчиков: от Kubernetes и Docker до почты и доступа ИИ-агентов к API.",
    contact: "Связаться",
    contactText:
      "По вопросам о проектах, ошибкам и предложениям пиши в Issues соответствующего репозитория на GitHub.",
    theme: "Переключить тему",
    language: "Read in English",
    intro: "Разработчик / Sipaha",
    headline: "Павел Симонов",
    lead: "Создаю инструменты для повседневной работы и делюсь исходным кодом. Здесь мои проекты и способы связаться со мной.",
    profile: "Мой GitHub",
    support: "Поддержать разработку",
    supportLead: "Любая сумма на твоё усмотрение. Спасибо за поддержку!",
    network: "Сеть",
    address: "Адрес получения",
    copy: "Скопировать адрес",
    copied: "Адрес скопирован",
    copyError: "Не удалось скопировать. Выдели адрес и скопируй его вручную.",
    qr: "QR-код адреса",
    instruction: "Отсканируй QR-код в своём кошельке или скопируй адрес.",
    check: "Выбирай указанную сеть при отправке.",
    bitcoin: "Обычный перевод в сети Bitcoin, без Lightning.",
    optional:
      "Донат добровольный и не даёт дополнительных прав или платных функций.",
    work: "То, над чем я работаю",
    workLead: "Открытые проекты для повседневных задач.",
    purpose: "На что идёт поддержка",
    purposeText:
      "На инструменты разработки, включая ИИ-подписки, и дальнейшую работу над проектами.",
    other: "Помочь можно и без доната",
    otherText:
      "Рассказать об ошибке, предложить улучшение или поделиться проектом. Всё это тоже помогает.",
    allProjects: "Все репозитории",
    footer: "Спасибо, что пользуешься моими проектами.",
    source: "Исходный код сайта",
    privacy: "Без аналитики и подключения кошелька.",
    boosty: "Поддержать на Boosty",
    boostyText: "Банковской картой через Boosty",
    crypto: "Или криптовалютой",
  },
  en: {
    title: "Pavel Simonov · Developer",
    description:
      "Pavel Simonov (Sipaha). Developer tools, open-source projects, and ways to support my work.",
    skip: "Skip to content",
    projectsNav: "Projects",
    supportNav: "Support",
    about: "About my work",
    aboutText:
      "I work on desktop apps and developer tools, from Kubernetes and Docker to email and controlled API access for AI agents.",
    contact: "Get in touch",
    contactText:
      "For project questions, bugs, and suggestions, open an issue in the relevant GitHub repository.",
    theme: "Switch theme",
    language: "Читать по-русски",
    intro: "Developer / Sipaha",
    headline: "Pavel Simonov",
    lead: "I build tools for everyday work and share the source. Here are my projects and where to find me.",
    profile: "Find me on GitHub",
    support: "Support development",
    supportLead: "Give any amount that feels right. Thank you!",
    network: "Network",
    address: "Receiving address",
    copy: "Copy address",
    copied: "Address copied",
    copyError: "Could not copy. Select the address and copy it manually.",
    qr: "Address QR code",
    instruction: "Scan the QR code with your wallet or copy the address.",
    check: "Choose the indicated network when sending.",
    bitcoin: "A regular Bitcoin transaction, not Lightning.",
    optional:
      "Donations are optional and do not unlock extra rights or paid features.",
    work: "What I’m working on",
    workLead: "Open-source projects for everyday tasks.",
    purpose: "What your support funds",
    purposeText:
      "Development tools, including AI subscriptions, and continued work on these projects.",
    other: "You can help without donating",
    otherText:
      "Report a bug, suggest an improvement, or share a project. It all makes a difference.",
    allProjects: "All repositories",
    footer: "Thanks for using my projects.",
    source: "Website source",
    privacy: "No analytics or wallet connection.",
    boosty: "Support on Boosty",
    boostyText: "Pay by bank card through Boosty",
    crypto: "Or with cryptocurrency",
  },
};
