export const content = {
  ru: {
    title: "Поддержать проекты · Павел Симонов",
    description:
      "Поддержать разработку проектов Павла Симонова (Sipaha). Публичные адреса, сети и QR-коды для донатов в одном месте.",
    skip: "К содержимому",
    projectsNav: "Проекты",
    theme: "Переключить тему",
    language: "Read in English",
    intro: "Привет, я Павел.",
    headline: "Делаю инструменты\nдля своей работы.",
    lead: "И делюсь ими с вами. Если мои проекты помогают тебе, можно поддержать их развитие.",
    profile: "Мой GitHub",
    support: "Поддержать разработку",
    supportLead: "Любая сумма на твоё усмотрение. Спасибо за поддержку!",
    network: "Сеть",
    address: "Адрес получения",
    copy: "Скопировать адрес",
    copied: "Адрес скопирован",
    copyError: "Не удалось скопировать. Выдели адрес и скопируй его вручную.",
    qr: "QR-код адреса",
    instruction: "Отсканируй QR-код в своём кошельке или скопируй адрес.",
    check: "Выбирай указанную сеть при отправке.",
    bitcoin: "Обычный перевод в сети Bitcoin, без Lightning.",
    optional:
      "Донат добровольный и не даёт дополнительных прав или платных функций.",
    work: "То, над чем я работаю",
    workLead: "Открытые проекты для повседневных задач.",
    purpose: "На что идёт поддержка",
    purposeText:
      "На инструменты разработки, включая ИИ-подписки, и дальнейшую работу над проектами.",
    other: "Помочь можно и без доната",
    otherText:
      "Рассказать об ошибке, предложить улучшение или поделиться проектом. Всё это тоже помогает.",
    allProjects: "Все репозитории",
    footer: "Спасибо, что пользуешься моими проектами.",
    source: "Исходный код сайта",
    privacy: "Без аналитики и подключения кошелька.",
    boosty: "Поддержать на Boosty",
    boostyText: "Банковской картой через Boosty",
    crypto: "Или криптовалютой",
  },
  en: {
    title: "Support my projects · Pavel Simonov",
    description:
      "Support open-source projects by Pavel Simonov (Sipaha). Donation addresses, networks, and QR codes in one place.",
    skip: "Skip to content",
    projectsNav: "Projects",
    theme: "Switch theme",
    language: "Читать по-русски",
    intro: "Hi, I’m Pavel.",
    headline: "Tools I build.\nTools you can use.",
    lead: "I build tools for my everyday work and share them. If they help you, you can support their development.",
    profile: "Find me on GitHub",
    support: "Support development",
    supportLead: "Give any amount that feels right. Thank you!",
    network: "Network",
    address: "Receiving address",
    copy: "Copy address",
    copied: "Address copied",
    copyError: "Could not copy. Select the address and copy it manually.",
    qr: "Address QR code",
    instruction: "Scan the QR code with your wallet or copy the address.",
    check: "Choose the indicated network when sending.",
    bitcoin: "A regular Bitcoin transaction, not Lightning.",
    optional:
      "Donations are optional and do not unlock extra rights or paid features.",
    work: "What I’m working on",
    workLead: "Open-source projects for everyday tasks.",
    purpose: "What your support funds",
    purposeText:
      "Development tools, including AI subscriptions, and continued work on these projects.",
    other: "You can help without donating",
    otherText:
      "Report a bug, suggest an improvement, or share a project. It all makes a difference.",
    allProjects: "All repositories",
    footer: "Thanks for using my projects.",
    source: "Website source",
    privacy: "No analytics or wallet connection.",
    boosty: "Support on Boosty",
    boostyText: "Pay by bank card through Boosty",
    crypto: "Or with cryptocurrency",
  },
};
